const express = require('express');
const {dashboardView } = require('../controllers/dashboardController');
const {disksView} = require('../controllers/disksController');
const {sharesView} = require('../controllers/sharesController');
const {usersView} = require('../controllers/usersController');
const {containersView} = require('../controllers/containersController');
const {vmsView} = require('../controllers/vmsController');
const {settingsView} = require('../controllers/settingsController');
const {logsView} = require('../controllers/logsController');
const router = express.Router();
router.get('/dashboard', dashboardView);
router.get('/disks', disksView);
router.get('/shares', sharesView);
router.get('/users', usersView);
router.get('/containers', containersView);
router.get('/vms', vmsView);
router.get('/settings', settingsView);
router.get('/logs', logsView);
module.exports = router;